Add Immutable flag to PendingIntents
Error: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]
NotificationHandlingService.makeMarkNotificationsSeenIntent(context), 0);

Explanation for issues of type "UnspecifiedImmutableFlag":
Apps targeting Android 12 and higher must specify either FLAG_IMMUTABLE or FLAG_MUTABLE when constructing a PendingIntent.

FLAG_IMMUTABLE is available since target SDK 23, and is almost always the best choice.
See:
https://developer.android.com/guide/components/intents-filters#CreateImmutablePendingIntents for a list of common exceptions to this rule.
https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
https://goo.gle/UnspecifiedImmutableFlag